-- BookReview PostgreSQL full schema
-- Source of truth used: models.py + app.py ensure_schema + schema.sql + migration 0001
-- This script is idempotent where practical (IF NOT EXISTS).

-- 1) Create database (run as superuser/admin role)
CREATE DATABASE bookreview;

-- 2) Connect to database (psql command)
-- \c bookreview
-- If your SQL client does not support \c, open a new connection to "bookreview" then run the remaining script.

-- 3) Core extensions (optional, safe for future usage)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 4) Tables

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(150) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_role CHECK (role IN ('user', 'admin'))
);

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    slug VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    slug VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS books (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    cover_url VARCHAR(512),
    description TEXT,
    genre VARCHAR(100),
    publisher VARCHAR(255),
    num_pages INTEGER,
    book_code VARCHAR(100) UNIQUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    category_id INTEGER REFERENCES categories(id),
    price NUMERIC(10, 2) NOT NULL DEFAULT 0,
    stock INTEGER NOT NULL DEFAULT 0,
    isbn VARCHAR(50) UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_books_price_non_negative CHECK (price >= 0),
    CONSTRAINT ck_books_stock_non_negative CHECK (stock >= 0),
    CONSTRAINT ck_books_num_pages_positive CHECK (num_pages IS NULL OR num_pages > 0)
);

CREATE TABLE IF NOT EXISTS reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    reviewer VARCHAR(255) NOT NULL,
    rating INTEGER NOT NULL,
    content TEXT,
    details TEXT,
    status VARCHAR(20) DEFAULT 'approved',
    moderated_at TIMESTAMP WITHOUT TIME ZONE,
    moderated_by VARCHAR(255),
    reject_reason TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_reviews_rating_range CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT ck_reviews_status CHECK (status IN ('approved', 'pending', 'rejected'))
);

CREATE TABLE IF NOT EXISTS book_tags (
    book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, tag_id)
);

CREATE TABLE IF NOT EXISTS bookmarks (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, book_id)
);

CREATE TABLE IF NOT EXISTS review_votes (
    review_id INTEGER NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL,
    PRIMARY KEY (review_id, user_id)
    -- TODO: app.py currently does not enforce FK from review_votes.user_id -> users.id
    -- Add FK after validating legacy data:
    -- , FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS review_comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id INTEGER NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
    parent_id INTEGER REFERENCES review_comments(id) ON DELETE CASCADE,
    author VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS review_reports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id INTEGER NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
    reporter_user_id INTEGER,
    reason TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
    -- TODO: app.py currently does not enforce FK from reporter_user_id -> users.id
);

CREATE TABLE IF NOT EXISTS audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    meta TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    subtotal NUMERIC(10, 2) NOT NULL DEFAULT 0,
    shipping_fee NUMERIC(10, 2) NOT NULL DEFAULT 0,
    discount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    total NUMERIC(10, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_orders_status CHECK (status IN ('pending', 'paid', 'cancelled', 'failed', 'completed')),
    CONSTRAINT ck_orders_subtotal_non_negative CHECK (subtotal >= 0),
    CONSTRAINT ck_orders_shipping_non_negative CHECK (shipping_fee >= 0),
    CONSTRAINT ck_orders_discount_non_negative CHECK (discount >= 0),
    CONSTRAINT ck_orders_total_non_negative CHECK (total >= 0)
);

CREATE TABLE IF NOT EXISTS order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id),
    book_id INTEGER NOT NULL REFERENCES books(id),
    title_snapshot VARCHAR(255) NOT NULL,
    unit_price NUMERIC(10, 2) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    line_total NUMERIC(10, 2) NOT NULL,
    CONSTRAINT ck_order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_order_items_unit_price_non_negative CHECK (unit_price >= 0),
    CONSTRAINT ck_order_items_line_total_non_negative CHECK (line_total >= 0)
);

CREATE TABLE IF NOT EXISTS payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id),
    provider VARCHAR(50) NOT NULL DEFAULT 'cod',
    amount NUMERIC(10, 2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    paid_at TIMESTAMP WITHOUT TIME ZONE,
    txn_ref VARCHAR(100) UNIQUE,
    CONSTRAINT ck_payments_amount_non_negative CHECK (amount >= 0),
    CONSTRAINT ck_payments_status CHECK (status IN ('pending', 'paid', 'failed', 'refunded', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS user_shelves (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    shelf_type VARCHAR(20) NOT NULL,
    added_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_shelves_user_book UNIQUE (user_id, book_id),
    CONSTRAINT ck_user_shelves_type CHECK (shelf_type IN ('read', 'reading', 'want_to_read'))
);

CREATE TABLE IF NOT EXISTS user_follows (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    following_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_follows_pair UNIQUE (follower_id, following_id),
    CONSTRAINT ck_user_follows_not_self CHECK (follower_id <> following_id)
);

CREATE TABLE IF NOT EXISTS user_activities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    activity_type VARCHAR(30) NOT NULL,
    target_id INTEGER,
    target_type VARCHAR(50),
    metadata TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_user_activities_type CHECK (
        activity_type IN ('review', 'shelf_add', 'shelf_move', 'follow', 'challenge_complete')
    )
);

CREATE TABLE IF NOT EXISTS reading_challenges (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    challenge_type VARCHAR(20) NOT NULL,
    target_count INTEGER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_reading_challenges_type CHECK (challenge_type IN ('yearly', 'monthly', 'weekly', 'custom')),
    CONSTRAINT ck_reading_challenges_target_positive CHECK (target_count > 0),
    CONSTRAINT ck_reading_challenges_date_range CHECK (end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS user_challenges (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    challenge_id INTEGER NOT NULL REFERENCES reading_challenges(id) ON DELETE CASCADE,
    current_count INTEGER DEFAULT 0,
    joined_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT uq_user_challenges UNIQUE (user_id, challenge_id),
    CONSTRAINT ck_user_challenges_count_non_negative CHECK (current_count >= 0)
);

CREATE TABLE IF NOT EXISTS book_views (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    viewed_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_book_views_user_book UNIQUE (user_id, book_id)
);

-- 5) Indexes (from SQLAlchemy index=True + app.py manual indexes + query patterns)

CREATE INDEX IF NOT EXISTS ix_users_username ON users(username);
CREATE INDEX IF NOT EXISTS ix_users_role ON users(role);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(email);

CREATE INDEX IF NOT EXISTS ix_categories_name ON categories(name);
CREATE INDEX IF NOT EXISTS ix_categories_slug ON categories(slug);

CREATE INDEX IF NOT EXISTS ix_tags_name ON tags(name);
CREATE INDEX IF NOT EXISTS ix_tags_slug ON tags(slug);

CREATE INDEX IF NOT EXISTS ix_books_title ON books(title);
CREATE INDEX IF NOT EXISTS ix_books_author ON books(author);
CREATE INDEX IF NOT EXISTS ix_books_created_at ON books(created_at);
CREATE INDEX IF NOT EXISTS ix_books_category_id ON books(category_id);
CREATE INDEX IF NOT EXISTS ix_books_book_code ON books(book_code);
CREATE INDEX IF NOT EXISTS ix_books_is_active ON books(is_active);

CREATE INDEX IF NOT EXISTS idx_reviews_book_id ON reviews(book_id);
CREATE INDEX IF NOT EXISTS ix_reviews_status ON reviews(status);
CREATE INDEX IF NOT EXISTS ix_reviews_created_at ON reviews(created_at);

CREATE INDEX IF NOT EXISTS ix_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS ix_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS ix_orders_created_at ON orders(created_at);

CREATE INDEX IF NOT EXISTS ix_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS ix_order_items_book_id ON order_items(book_id);

CREATE INDEX IF NOT EXISTS ix_payments_order_id ON payments(order_id);
CREATE INDEX IF NOT EXISTS ix_payments_status ON payments(status);

CREATE INDEX IF NOT EXISTS idx_user_shelves_user_id ON user_shelves(user_id);
CREATE INDEX IF NOT EXISTS idx_user_shelves_book_id ON user_shelves(book_id);
CREATE INDEX IF NOT EXISTS idx_user_shelves_type ON user_shelves(shelf_type);

CREATE INDEX IF NOT EXISTS idx_user_follows_follower ON user_follows(follower_id);
CREATE INDEX IF NOT EXISTS idx_user_follows_following ON user_follows(following_id);

CREATE INDEX IF NOT EXISTS idx_user_activities_user_id ON user_activities(user_id);
CREATE INDEX IF NOT EXISTS idx_user_activities_type ON user_activities(activity_type);
CREATE INDEX IF NOT EXISTS idx_user_activities_created_at ON user_activities(created_at);

CREATE INDEX IF NOT EXISTS idx_user_challenges_user_id ON user_challenges(user_id);
CREATE INDEX IF NOT EXISTS idx_user_challenges_challenge_id ON user_challenges(challenge_id);
CREATE INDEX IF NOT EXISTS idx_reading_challenges_active ON reading_challenges(is_active);

CREATE INDEX IF NOT EXISTS idx_book_views_user_id ON book_views(user_id);
CREATE INDEX IF NOT EXISTS idx_book_views_book_id ON book_views(book_id);
CREATE INDEX IF NOT EXISTS idx_book_views_viewed_at ON book_views(viewed_at);

CREATE INDEX IF NOT EXISTS ix_review_comments_review_id ON review_comments(review_id);
CREATE INDEX IF NOT EXISTS ix_review_comments_parent_id ON review_comments(parent_id);
CREATE INDEX IF NOT EXISTS ix_review_reports_review_id ON review_reports(review_id);
CREATE INDEX IF NOT EXISTS ix_review_votes_user_id ON review_votes(user_id);
CREATE INDEX IF NOT EXISTS ix_bookmarks_book_id ON bookmarks(book_id);

-- 6) Seed data (from app.py _ensure_database_exists and default challenge seeds)

INSERT INTO books (title, author, cover_url, description)
VALUES
    ('Atomic Habits', 'James Clear', 'https://images-na.ssl-images-amazon.com/images/I/51-uspgqWIL._SX329_BO1,204,203,200_.jpg', 'Cách hình thành thói quen tốt và loại bỏ thói quen xấu bằng các bước nhỏ.'),
    ('Deep Work', 'Cal Newport', 'https://images-na.ssl-images-amazon.com/images/I/41j8QX8+lfL._SX331_BO1,204,203,200_.jpg', 'Làm việc sâu để đạt hiệu suất cao trong thế giới nhiễu loạn.'),
    ('Clean Code', 'Robert C. Martin', 'https://images-na.ssl-images-amazon.com/images/I/41xShlnTZTL._SX374_BO1,204,203,200_.jpg', 'Nguyên tắc viết mã sạch cho lập trình viên chuyên nghiệp.')
ON CONFLICT DO NOTHING;

INSERT INTO users (username, email, password_hash, role)
VALUES
    -- Password hash is copied from existing app seed behavior (do not use in production).
    ('admin', 'admin@example.com', 'scrypt:32768:8:1$replace_me$replace_me', 'admin'),
    ('customer_demo', 'customer@example.com', 'scrypt:32768:8:1$replace_me$replace_me', 'user')
ON CONFLICT (username) DO NOTHING;

-- NOTE:
-- Replace password_hash values above by running app-level registration/reset flow,
-- or generate hashes via Werkzeug before production use.

INSERT INTO reading_challenges (title, description, challenge_type, target_count, start_date, end_date, is_active)
VALUES
    ('Thử thách đọc review hằng năm', 'Đọc review của 12 cuốn sách trong năm', 'yearly', 12, DATE '2026-01-01', DATE '2026-12-31', TRUE),
    ('Thử thách tháng này', 'Đọc review của 2 cuốn sách trong tháng này', 'monthly', 2, DATE '2026-01-01', DATE '2026-01-31', TRUE),
    ('Thử thách tuần này', 'Đọc review của 1 cuốn sách trong tuần này', 'weekly', 1, DATE '2026-01-01', DATE '2026-01-07', TRUE)
ON CONFLICT DO NOTHING;

-- 7) Additional TODO notes
-- TODO: Current codebase uses mixed sqlite3 raw SQL and SQLAlchemy models.
-- TODO: Consider creating SQLAlchemy models for reviews/tags/social/challenge tables for single source of truth.
-- TODO: No dedicated session/token persistence table found in current schema (token appears signed by itsdangerous).
